[package]
name = "bpi-bare-bones-rust"
version = "0.1.0"
authors = ["Alexey Denisov <rtgbnm@gmail.com>"]
edition = "2018"

[[bin]]
name = "bpi-boot"
path = "src/boot.rs"

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
